# This is a basic workflow to help you get started with Actions
name: india_air_quality_json

# Controls when the workflow will run
on:
  push:  # Runs the workflow on push to the main branch
    branches:
      - main
  pull_request:  # Runs on pull requests to the main branch
    branches:
      - main
 # workflow_dispatch:  # Allows manual execution of the workflow
 # schedule:
 #   - cron: '45 * * * *'  # Runs every 45th minute of the hour

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "snowflake-snowpark-python[pandas]" requests pandas

      - name: Run data ingestion script
        run: |
          echo "Starting Weatherbit API data ingestion..."
          python ingest-api-data.py
